name = "Euler"
uuid = "b89150e2-eaf9-465b-9441-5d87950230c7"
authors = ["kwj <kwj@vlax.net>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"

[compat]
Combinatorics = "=1.0.2"
DataStructures = "0.19.1"
Primes = "0.5.7"
